<<<<<<< HEAD
version: "2"
services:
  my-wpdb:
    image: mysql
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  my-wp:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - "8082:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: root
