version: "2"
services:
  wordpress:
   image: wordpress
   ports: 
     - 8084:80
   environment:
     WORDPRESS_DB_PASSWORD: abc123
   

  mysql:
   image: mysql:latest
   environment:
    MYSQL_ROOT_PASSWORD: abc123

  links:
      - mysql:mysql
